# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sWTV2X3StjQM8Ccd6Je8R4XEViE1_Rej
"""

import numpy as np
import pandas as pd
import seaborn as sns

store = pd.read_csv("store.csv")

store.info()

s1.query('Ship_Mode == "Second Class" and Category == "Technology"')["Quantity"].sum()

s1

s1.info()

s1["Ship_Mode"] = s1["Ship_Mode"].astype(dtype="string")
s1["Category"] = s1["Category"].astype(dtype="string")

s1.info()

store["Order Date"] = pd.to_datetime(store["Order Date"])

store.info()

store.head()

store["Year"] = store["Order Date"].dt.year
store["Month"] = store["Order Date"].dt.month
s3 = store.groupby(["Year","Month"])["Profit"].aggregate(["sum"])
s3

(s3.query("Year == 2017").aggregate(["sum"]) - s3.query("Year == 2016").aggregate(["sum"]) / s3.query("Year == 2016").aggregate(["sum"]))*100

s3.query("Year == 2017").aggregate(["sum"])

s3.query("Year == 2016").aggregate(["sum"])

((( s3.query("Year == 2017").aggregate(["sum"]) - s3.query("Year == 2016").aggregate(["sum"]) )
/ s3.query("Year == 2016").aggregate(["sum"]) ) *100).rename(columns={"sum":"Profit%"})

# 14 Percent increase in profit